name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:
  style-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint with black
        run: |
          pip install black
          black --check -l 120 .